Repository Klimatbyran/frontend, pull requests merged in 2025-06, with the labels that each got.

#803 [799] update link for municipality bike lane data
  src/locales/sv/translation.json
Labels: bug

#810 [fix] update English link to municipality bike lane data
  src/locales/en/translation.json
Labels: bug

#813 adding check for verification of scope 3 total too, not just categories
  src/hooks/useVerificationStatus.ts
Labels: bug

#816 [fix] restyle company bar chart
  src/components/companies/sectors/charts/SectorEmissionsChart.tsx
  src/components/graphs/BarChart.tsx
Labels: bug

#820 [fix] allow for several issues to be shown per company on the validation dashboard
  src/hooks/useValidationReports.ts
  src/pages/ValidationDashboard.tsx
Labels: bug

#831 [fix] correct municipality charging point source link
  src/components/methods/content/SourcesContent.tsx
  src/hooks/useMunicipalityKPIs.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: bug

#834 added frontend functionality for testing out the emissions assessment
  src/components/companies/detail/emissions-assessment/EmissionsAssessmentButton.tsx
  src/components/companies/detail/emissions-assessment/EmissionsAssessmentDialog.tsx
  src/components/companies/detail/emissions-assessment/YearSelectionModal.tsx
  src/components/companies/detail/overview/CompanyOverview.tsx
  src/hooks/companies/useEmissionsAssessment.ts
  src/lib/api-types.ts
  src/lib/api.ts
Labels: enhancement

#858 [chore] Run prettier on the code
  src/components/companies/detail/emissions-assessment/EmissionsAssessmentButton.tsx
  src/components/companies/detail/emissions-assessment/EmissionsAssessmentDialog.tsx
  src/components/companies/detail/emissions-assessment/YearSelectionModal.tsx
  src/components/companies/edit/test/editor-logic.test.tsx
  src/components/companies/sectors/trends/TrendCard.tsx
  src/components/companies/sectors/trends/TrendCards.tsx
  src/components/companies/sectors/trends/TrendCompanyList.tsx
  src/components/layout/InfoTooltip.tsx
  src/components/layout/Selector.tsx
  src/components/methods/content/CompanyDataOverview.tsx
  src/components/methods/content/DataCollectionProcess.tsx
  src/components/methods/content/EmissionsCategories.tsx
  src/components/methods/content/HistoricalData.tsx
  src/components/municipalities/MunicipalityStatCard.tsx
  src/components/products/DownloadCard.tsx
  src/components/products/DownloadControls.tsx
  src/data-guide/ProgressiveDataGuideMobile.tsx
  src/pages/SupportPage.tsx
Labels: chore

#865 Utsläpps -> utsläpp (copy)
  src/locales/sv/translation.json
Labels: copy edit
