Repository Klimatbyran/frontend, pull requests merged in 2025-09, with the labels that each got.

#995 [705] Added linking from landing top lists to municipality and companies
  src/components/RankedList.tsx
  src/components/layout/Header.tsx
  src/pages/LandingPage.tsx
  src/routes.tsx
Labels: enhancement

#999 [Fix] broken methodology navigation
  src/components/methods/MethodNavigation.tsx
  src/pages/MethodsPage.tsx
Labels: bug

#1008 [1007] update swedish carbon law copy
  src/components/methods/content/CarbonLaw.tsx
  src/locales/sv/translation.json
Labels: chore

#998 [996] update frontend to match municipality methodology
  src/components/methods/MethodContent.tsx
  src/components/methods/content/CO2BudgetsContent.tsx
  src/components/methods/content/MunicipalityDataOverview.tsx
  src/components/methods/content/MunicipalityKPIsContent.tsx
  src/components/municipalities/emissionsGraph/CustomTooltip.tsx
  src/components/municipalities/list/MunicipalityCard.tsx
  src/components/municipalities/sectorChart/MunicipalitySectorLegend.tsx
  src/lib/methods/methodologyData.ts
  src/locales/dataguide/en/municipalityCanWeExtendCarbonBudget.md
  src/locales/dataguide/en/municipalityTotalEmissions.md
  src/locales/dataguide/en/municipalityWhatIsCarbonBudget.md
  src/locales/dataguide/sv/co2units.md
  src/locales/dataguide/sv/municipalityCanWeExtendCarbonBudget.md
  src/locales/dataguide/sv/municipalityTotalEmissions.md
  src/locales/dataguide/sv/municipalityWhatIsCarbonBudget.md
  src/locales/en/dataguideItems.json
  src/locales/en/translation.json
  src/locales/sv/dataguideItems.json
  src/locales/sv/translation.json
  src/pages/MethodsPage.tsx
  src/pages/MunicipalityDetailPage.tsx
Labels: enhancement, chore

#1012 [968] add political rule to municipality detailed page
  src/data-guide/items.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/MunicipalityDetailPage.tsx
Labels: enhancement

#1028 [1019] add meets paris to municipality list card
  src/components/municipalities/list/MunicipalityCard.tsx
  src/components/municipalities/list/MunicipalityCardInfo.tsx
  src/components/municipalities/list/MunicipalityList.tsx
  src/locales/sv/translation.json
  src/types/municipality.ts
Labels: enhancement

#1035 [1020] Adjusted left margin to counter legend clipping
  src/components/municipalities/emissionsGraph/OverviewChart.tsx
  src/components/municipalities/emissionsGraph/SectorsChart.tsx
Labels: bug

#1032 Fix merge conflicts from muni method change
  src/components/municipalities/MunicipalityEmissions.tsx
  src/components/municipalities/list/MunicipalityList.tsx
  src/components/municipalities/list/MunicipalityListFilter.tsx
  src/data-guide/items.ts
  src/hooks/municipalities/useMunicipalities.ts
  src/lib/api-types.ts
  src/locales/dataguide/en/co2units.md
  src/locales/dataguide/en/municipalityAnnualEmissionChangeSince2015.md
  src/locales/dataguide/en/municipalityCanWeExtendCarbonBudget.md
  src/locales/dataguide/en/municipalityReductionNeededForParisAgreement.md
  src/locales/dataguide/en/municipalityWhatIsCarbonBudget.md
  src/locales/dataguide/sv/municipalityAnnualEmissionChangeSince2015.md
  src/locales/dataguide/sv/municipalityCanWeExtendCarbonBudget.md
  src/locales/dataguide/sv/municipalityPredicatedNetZeroDate.md
  src/locales/dataguide/sv/municipalityReductionNeededForParisAgreement.md
  src/locales/dataguide/sv/municipalityWhatIsCarbonBudget.md
  src/locales/en/dataguideItems.json
  src/locales/sv/dataguideItems.json
  src/locales/sv/translation.json
  src/pages/LandingPage.tsx
  src/pages/MunicipalitiesComparePage.tsx
  src/pages/MunicipalityDetailPage.tsx
  src/types/municipality.ts
Labels: bug, chore

#1054 [Prod] Prod Major Release 5.0.0
  package-lock.json
  package.json
Labels: prod release

#1058 [fix] rename municipality sectors
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: enhancement, copy edit
