Repository Klimatbyran/frontend, pull requests merged in 2025-05, with the labels that each got.

#682 681 Move municipality line graph legend
  src/components/municipalities/MunicipalityEmissionsGraph.tsx
  src/pages/MunicipalityDetailPage.tsx
Labels: bug

#686 Feat remove municipality ranking needed emissions percent
  src/hooks/useMunicipalityKPIs.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: enhancement

#693 [fix] Update Municipality Ranked List
  src/pages/LandingPage.tsx
Labels: bug

#692 [#691] Improve company and municipality card grid performance
  package-lock.json
  package.json
  src/components/CardGrid.tsx
  src/components/companies/list/CompanyList.tsx
  src/components/municipalities/list/MunicipalityList.tsx
  src/pages/CompaniesPage.tsx
Labels: enhancement

#697 [#696] Fix company card layout through container queries
  package-lock.json
  package.json
  src/components/companies/list/CompanyCard.tsx
  tailwind.config.js
Labels: bug

#703 FIX change municipality card KPI colors to match rest of site
  src/components/municipalities/list/MunicipalityCard.tsx
Labels: bug

#716 715 conditional coloring of municipality needed emissions percent
  src/pages/MunicipalityDetailPage.tsx
Labels: bug

#718 717 add conditional coloring of municipality EVCP
  src/pages/MunicipalityDetailPage.tsx
Labels: bug

#725 Fix editor not saving
  package-lock.json
  package.json
  src/components/companies/edit/CompanyEditScope1.tsx
  src/components/companies/edit/CompanyEditScope3.tsx
  src/lib/company-edit.ts
Labels: Urgent!

#677 [#599] Data guide
  src/App.tsx
  src/components/companies/detail/CompanyScope3.tsx
  src/components/layout/ScrollToTop.tsx
  src/data-guide/DataGuide.tsx
  src/data-guide/DataGuideContent.tsx
  src/data-guide/GuideSheet.tsx
  src/data-guide/GuideSidebar.tsx
  src/data-guide/SidebarGuideItem.tsx
  src/data-guide/guide-item-helpers.tsx
  src/data-guide/guide-items.tsx
  src/data-guide/internal.ts
  src/data-guide/useDataGuide.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/CompanyDetailPage.tsx
Labels: enhancement

#743 [228] municipality sector emissions
  src/components/municipalities/MunicipalityEmissionsGraph.tsx
  src/components/municipalities/MunicipalitySectorLegend.tsx
  src/components/municipalities/MunicipalitySectorPieChart.tsx
  src/components/municipalities/MunicipalitySectorTooltip.tsx
  src/hooks/useMunicipalitySectorEmissions.ts
  src/hooks/useMunicipalitySectors.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/MunicipalityDetailPage.tsx
  src/types/municipality.ts
Labels: enhancement

#751 [746] municipality sector pie chart add more years
  src/components/companies/detail/Scope3Data.tsx
  src/components/layout/YearSelector.tsx
  src/pages/MunicipalityDetailPage.tsx
Labels: enhancement

#752 [747] add sectors to municipality emissions history graph
  src/components/municipalities/CustomTooltip.tsx
  src/components/municipalities/DataViewSelector.tsx
  src/components/municipalities/MunicipalityEmissions.tsx
  src/components/municipalities/MunicipalityEmissionsGraph.tsx
  src/components/municipalities/OverviewChart.tsx
  src/components/municipalities/SectorsChart.tsx
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/MunicipalityDetailPage.tsx
Labels: enhancement

#784 [fix] remove duplicate municipality sector emissions pie chart
  src/pages/MunicipalityDetailPage.tsx
Labels: bug

#783 [581] update consumption emissions strings
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: enhancement

#789 [fix] adapt company editor to overflowing reporting periods
  src/components/companies/edit/CompanyEditRow.tsx
  src/pages/CompanyEditPage.tsx
Labels: bug
