Repository Klimatbyran/frontend, pull requests merged in 2025-08, with the labels that each got.

#913 [fix] Make all cards on landing page have same margins left and right on mobile
  src/pages/LandingPage.tsx
Labels: bug

#912 [806] Handle null values in municipality rankings
  src/components/municipalities/map/SwedenMap.tsx
  src/components/municipalities/rankedList/KPIDetailsPanel.tsx
  src/components/municipalities/rankedList/MunicipalityInsightsList.tsx
  src/components/municipalities/rankedList/MunicipalityInsightsPanel.tsx
  src/components/municipalities/rankedList/MunicipalityRankedList.tsx
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/types/municipality.ts
Labels: bug, Good for Volunteers

#911 [652] Added Newsletter Archive page
  package-lock.json
  package.json
  src/components/layout/Header.tsx
  src/components/newsletters/NewsletterNavigation.tsx
  src/components/ui/pagination.tsx
  src/hooks/useNewsletters.ts
  src/lib/api-types.ts
  src/lib/api.ts
  src/lib/newsletterArchive/newsletterData.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/NewslettersPage.tsx
  src/routes.tsx
  src/utils/itemPagination.tsx
Labels: enhancement

#929 [928] restyle data guide
  src/data-guide/ProgressiveDataGuide.tsx
  src/data-guide/ProgressiveDataGuideMobile.tsx
  src/data-guide/SectionWithHelp.tsx
  src/locales/sv/translation.json
Labels: bug

#861 [832] Sticky company/municipality name in header on scroll
  src/components/layout/Header.tsx
  src/hooks/useHeaderTitle.ts
Labels: enhancement

#953 [951] Misalignment of emissions and emissions change values on company cards
  src/components/companies/list/CompanyCard.tsx
Labels: bug

#962 [960] prevent labels from overflowing report card
  src/components/layout/ContentCard.tsx
Labels: bug

#961 [bug] minor error fixes in report landing page
  src/pages/ReportLandingPage.tsx
Labels: bug

#967 [965] Change to subscribe button translations, added button to newsletterpage
  src/components/layout/Header.tsx
  src/components/newsletters/NewsletterNavigation.tsx
  src/components/ui/pagination.tsx
  src/locales/en/translation.json
  src/locales/sv/translation.json
  src/pages/NewslettersPage.tsx
Labels: enhancement, requested change

#978 [fix] Add Madeleine to board
  public/people/madeleine.png
  src/hooks/useBoardMembers.ts
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: enhancement

#980 [Fix] Switched placed on conditional unit display
  src/components/companies/detail/overview/CompanyOverview.tsx
Labels: bug

#981 [Prod] Minor Version Bump v4.7.0
  package-lock.json
  package.json
Labels: prod release

#973 970 fix municipality pie chart tooltip update by creating new reusable component
  src/components/companies/CompanyPieChartView.tsx
  src/components/graphs/tooltips/PieTooltip.tsx
  src/components/municipalities/sectorChart/MunicipalitySectorPieChart.tsx
  src/components/municipalities/sectorChart/MunicipalitySectorTooltip.tsx
  src/locales/en/translation.json
  src/locales/sv/translation.json
Labels: bug, enhancement

#982 [chore] update deps
  package-lock.json
  package.json
Labels: chore

#983 [Prod] Patch Version Bump v4.7.1
  package-lock.json
  package.json
Labels: prod release

#986 [fix] hide trend explanation from company emissions graph for now
  src/components/companies/detail/history/EmissionsHistory.tsx
Labels: bug

#987 [fix] make comapny scope and sector line graphs appear again
  src/components/companies/detail/history/EmissionsLineChart.tsx
Labels: bug

#990 [fix] hide data selector from company emissions chart header
  src/components/companies/detail/history/ChartHeader.tsx
Labels: bug

#991 [fix] correct madeleines surname
  src/hooks/useBoardMembers.ts
Labels: bug
